setup.ilm.enabled: false

#=========================== Filebeat inputs =============================

filebeat.inputs:
- type: log
  enabled: true
  include_lines: ['.*ERROR*.']
  paths:
    - /var/tmp/log/apps/apps-status/*.log
  fields:
    application: app-status
    type: error


- type: log
  enabled: true
  include_lines: ['.*ERROR*.']
  paths:
    - /var/tmp/log/apps/apps-status1/*.log
  fields:
    application: app-status1
    type: error

#============================= Filebeat modules ===============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.kafka:
  hosts: ["localhost:7092"]
  topic: 'filebeat'
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

processors:
  - add_host_metadata: ~
