spring:
 application:
  name: log-monitor

 mail:  host: 172.17.6.199
  port: 25
  properties:
    mail.smtp.auth: false
    mail.smtp.starttls.enable: false

logging:
  level:
    root: info
    poc.kafka: debug  file: /var/tmp/apps/log-monitor/log-monitor

app:
  mail:
    from: tcs_abhosle@vendor.nse.co.in
    to: tcs_abhosle@vendor.nse.co.in
    subject: '{0} service is having some issues on {1} server'

kafka:
  kafkaConsumer:
    bootstrap.servers: '172.17.5.36:7092'
    group.id: 'test-consumers'
    fetch.min.bytes: 100000
    session.timeout.ms: 60000
    auto.offset.reset: 'earliest'
    key.deserializer: 'org.apache.kafka.common.serialization.IntegerDeserializer'
    value.deserializer: 'org.apache.kafka.common.serialization.StringDeserializer'

